[package]
name = "assert2-ify"
version = "0.1.0"
authors = ["geo-ant <54497890+geo-ant@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["assert2-ify-macros"]

[dependencies]
assert2-ify-macros = {path="./assert2-ify-macros", version = "0.1.0"}
assert2 = "0.3"